In [1]:
import numpy as np

In [3]:
#create a 3x3 array
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr = np.array([1.1,1.2,3.3])
arrint = np.array([1.1,1.2,3.3], dtype='int32')
print(arr)
print(arr.astype('int32'))
print(arr)
print("convert to integer")
print(arrint)

[1.1 1.2 3.3]
[1 1 3]
[1.1 1.2 3.3]
convert to integer
[1 1 3]


In [23]:
# FAncy indexing to extract even
arre = np.array([1, 2, 3, 4, 5, 6])
# print(arre[1 : :2])
print(arre[[1, 3, 5]])

[2 4 6]


In [14]:
# rehape 1d og 9 element to 3x3
nd = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
nd.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])